site_name: Chandhar Research Labs <small> Pvt. Ltd.</small>
site_description: Research, Innovation, and Product Development in Wireless and SDR Systems
site_author: Chandhar Research Labs Pvt Ltd
site_url: https://docs.chandhar-labs.com


theme:
  name: material
  font:
    text: Inter
    code: Roboto Mono
  logo: assets/images/logo.png   # optional
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      
extra:
  generator: false
  toc_title: "On this page"
      
      
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Research:
      - Research-Overview: research/index.md
      - Research Areas:
          - 5G Use Cases: research/areas/5g-use-cases.md
          - 5G Security: research/areas/5g-security.md
          - 5G Enabled Drones: research/areas/5g-drones.md
          - Deep Learning for Wireless: research/areas/dl-wireless.md
          - Spectrum Management: research/areas/spectrum-management.md
          - IoT Security: research/areas/iot-security.md

      
  - Products:
      - Products-Overview: products/index.md
      - 5-Nines Radio (5G Testbed): products/5-nines-radio.md
      - Deep Radio: products/deep-radio.md
      - Wi-Guy: products/wi-guy.md
      - Loiter (5G Drone): products/loiter.md
      - IoT Security Testbed: products/iot-security-testbed.md
      - 5NR-NSMEC: products/5nr-nsmec.md
      - 5G Enabled E-Vehicle: products/5g-ev.md


  - Workshops:
      - Workshops-Overview: workshops/index.md
      - Deep Learning for Wireless: workshops/Deep-Radio.md
      - 5G Hands-On: workshops/5g-hands-on.md

  - Publications:
      - Publications-Overview: publications/index.md
      - Books: publications/books-publications.md
      - Journal Publications: publications/journal-publications.md
      - Conference Publications: publications/conference-publications.md

  - Chandhar Research Press:
      - Chandhar Research Press-Overview: press/index.md
      - Journals:
        - JEWS: press/jews.md
      - Books:
        - LTE Hands-On: press/lte-hands-on.md
        - 5G NR Hands-On: press/5g-nr-hands-on.md
      - Standards & Specifications:
        - YesDR Standard: press/yesdr.md



      

  - Internships:
      - Internships-Overview: internships/index.md
      - Past & Current Internships: internships/past-current.md
      - Visitng Scholars: internships/visiting-scholars.md
      
      

  - Talks:
      - Talks-Overview: talks/index.md
      - Talks: talks/talks.md
      - Tutorials: talks/tutorials.md
      - Workshops: talks/workshops.md
 
  - About Us: 
    - About Us: about/company.md
    - Contact Us: about/contact.md
  #- Gallery: more/gallery.md
  #- Links: more/links.md
  #- Saro Farms: more/saro farms.md
  #- CRFO: more/crfo.md


markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search

copyright: >
  © 2018–2026 Chandhar Research Labs Pvt. Ltd. All rights reserved.

